config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  validates_presence_of :title, :description, :user_id

  has_attached_file :image, styles: { medium: "300x300>", large: "600x600>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def votes
    self.get_likes.size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_pin, only: [:show, :upvote]
  before_action :find_users_pin, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      flash[:success] = 'Pin was created successfully'
      redirect_to :root
    else
      flash[:warning] = 'Pin was not created'
      render :new, status: 400
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      flash[:success] = 'Pin was updated successfully'
      redirect_to @pin
    else
      flash[:warning] = 'Pin was not updated'
      render :edit, status: 400
    end
  end

  def destroy
    @pin.delete
    redirect_to :root
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to @pin
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def find_users_pin
    begin
      @pin = current_user.pins.find(params[:id])
    rescue
      flash[:warning] = 'Invalid pin, or you are not the owner'
      @pin = Pin.find(params[:id])
      redirect_to @pin
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pin Board
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Pin Board", root_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Pin", new_pin_path
          %li.dropdown
            = link_to "#", class: "dropdown-toggle", role: "button", data: {toggle: "dropdown"} do
              = current_user.email
              %span.caret
            %ul.dropdown-menu{role:"menu"}
              %li= link_to "Account Settings", edit_user_registration_path
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign In", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path

  .container
    - flash.each do |name, msg|
      %div{class: "alert alert-#{name}"}
        =link_to "×", "#", class: "close", data: {dismiss: "alert"}
        %strong= "#{name.titlecase}:"
        = msg
    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    .alert.alert-warning#errors
      %strong
        = pluralize(@pin.errors.count, "error")
        prevented this Pin from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  .form-group
    = f.input :title, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' } 

  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#pin_edit.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Pin
      .panel-body
        = image_tag @pin.image.url(:medium)
        = render 'form'
      .panel-footer
        = @pin.user.email

app/views/pins/index.html.haml
%h1 Welcome to Pin Board
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url(:medium)), pin
      .panel-body
        %h2= link_to pin.title, pin
      .user
        = pin.user.email

app/views/pins/new.html.haml
#pin_new.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Pin
      .panel-body
        = render 'form'
      .panel-footer
        = current_user.email

app/views/pins/show.html.haml
#pin_show.panel.panel-default
  %h1= @pin.title
  = image_tag @pin.image.url(:large), class: "pin_image"
  .panel-body
    %p.description= @pin.description
  .panel-footer
    .user.pull-left
      = @pin.user.email
    .btn-group.pull-right
      = link_to like_pin_path(@pin), method: :put, class: "btn btn-primary" do
        %span.glyphicon.glyphicon-heart
          = @pin.get_upvotes.size
      = link_to "Edit", edit_pin_path, class: "btn btn-warning"
      = link_to "Delete", pin_path, method: :delete, class: "btn btn-danger"